#!/bin/bash

# ==============================================================================
# setup_bridge.sh
#
# This script configures a network bridge 'br0' using netplan.
# It makes the host's physical network interface a member of the bridge,
# which is necessary for KVM/QEMU virtual machines to access the LAN directly.
#
# Usage: sudo ./setup_bridge.sh <interface_name>
# Example: sudo ./setup_bridge.sh enp3s0
# ==============================================================================

# --- Configuration ---
# The name of the new Netplan configuration file.
NETPLAN_FILE="/etc/netplan/01-br0-bridge.yaml"


# --- Pre-flight Checks ---

# 1. Check for root privileges
if [ "$EUID" -ne 0 ]; then
  echo "❌ This script must be run with sudo or as root."
  exit 1
fi

# 2. Check for the interface name argument
if [ -z "$1" ]; then
  echo "❌ Error: You must provide the physical interface name as an argument."
  echo "   -> How to find it: Run 'ip -br addr'"
  echo "   -> Usage: sudo $0 <interface_name>"
  echo "   -> Example: sudo $0 enp3s0"
  exit 1
fi

# Assign the first argument to the INTERFACE variable
INTERFACE=$1


# --- Main Logic ---

echo "▶️  Configuring bridge 'br0' for interface '$INTERFACE'..."

# Create the netplan YAML configuration file using a 'here document'.
# This configuration does the following:
# 1. Takes the IP configuration (DHCP) away from the physical interface.
# 2. Creates the bridge 'br0'.
# 3. Adds the physical interface as a port on the bridge.
# 4. Assigns the IP configuration (DHCP) to the bridge itself.
cat > $NETPLAN_FILE << EOF
# This file was generated by the setup_bridge.sh script.
network:
  version: 2
  renderer: networkd
  ethernets:
    $INTERFACE:
      dhcp4: no
      dhcp6: no
  bridges:
    br0:
      interfaces: [$INTERFACE]
      dhcp4: yes
EOF

echo "✅ Netplan configuration file created at '$NETPLAN_FILE'."
echo "Applying new network configuration... (This may cause a brief disconnect)"


echo "Run 'ip -br addr' to verify that 'br0' is up and has an IP address."

# Apply the new netplan configuration.
netplan apply

echo "✅ Configuration applied successfully!"
